name: 'Andrew Crittenden '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13401078223250806
title: Z-Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#fff61b'
    - '#8f4369'
    - '#d88b2f'
  brandStrength: 0.8864163199905306
  lightness: 0.4726067543961108
  saturation: 0.9795094816945493
  rhythmicContrast: 0.671338009648025
purpose: []
